export const ReadingLevels = [
    {
        id: 1,
        level: "N5",
        title: "Starter",
        desc: "Foundations",
        kanji: "~ 100 kanji",
        bg: "bg-cyan-bg",
        color: "text-cyan-500",
        nextPath: "/reading/modules",
    },
    {
        id: 2,
        level: "N4",
        title: "Beginner",
        desc: "Basic conversations",
        kanji: "~ 200 kanji",
        bg: "bg-amber-bg",
        color: "text-amber-500",
        nextPath: "/reading/modules",
    },
    {
        id: 3,
        level: "N3",
        title: "Intermediate",
        kanji: "~ 600 kanji",
        desc: "More complex topics",
        bg: "bg-pink-bg",
        color: "text-pink-500",
        nextPath: "/reading/modules",
    },
];

export const KanjiLevels = [
    {
        id: 1,
        level: "N5",
        title: "Starter",
        desc: "~ 100 kanji",
        bg: "bg-cyan-bg",
        color: "text-cyan-500",
        nextPath: "/kanji/modules",
    },
    {
        id: 2,
        level: "N4",
        title: "Beginner",
        desc: "~ 200 kanji",
        bg: "bg-amber-bg",
        color: "text-amber-500",
        nextPath: "/kanji/modules",
    },
    {
        id: 3,
        level: "N3",
        title: "Intermediate",
        desc: "~ 600 kanji",
        bg: "bg-pink-bg",
        color: "text-pink-500",
        nextPath: "/kanji/modules",
    },
];
